services:
  web:
    container_name: web
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
      - 3001
    ports:
      - 3001:3001
    image: anishnath/palkadot-scan-web
    links:
      - api
  api:
    container_name: api
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    expose:
      - 3000
    ports:
      - 3000:3000
    image: anishnath/palkadot-scan-api
    labels:
      generated: by 8gwifi.org
version: '3'
